# Jekyll
collections:
    - pages
encoding: utf-8
exclude:
    - LICENSE
    - README.md
    - gulpfile.js
    - node_modules
    - npm-debug.log
    - package-lock.json
    - package.json
    - scss
    - yarn.lock
markdown: kramdown
timezone: Europe/Stockholm

# Site variables
analytics: UA-55203713-1
enforce_ssl: hlilje.com
title: hlilje
url: https://hlilje.com
url_short: hlilje.com
