# Jekyll
encoding: utf-8
exclude:
    - bower.json
    - gulpfile.js
    - LICENSE
    - package.json
    - README.md
markdown: kramdown
timezone: Europe/Stockholm

# Site variables
analytics: UA-55203713-1
enforce_ssl: hlilje.com
title: hlilje
url: https://hlilje.com
url_short: hlilje.com
