# Jekyll
encoding: utf-8
markdown: kramdown
timezone: Europe/Stockholm
exclude:
    - bower.json
    - gulpfile.js
    - LICENSE
    - package.json
    - README.md

# Site variables
title: hlilje
url: https://hlilje.com
url_short: hlilje.com
enforce_ssl: hlilje.com
analytics: UA-55203713-1
